[project]
name = "imp-semantics"
version = "0.1.0"
source = "k-src"

[targets.llvm]
backend = "llvm"
main-file = "statements.k"
main-module = "STATEMENTS"
syntax-module = "STATEMENTS-SYNTAX"

[targets.haskell]
backend = "haskell"
main-file = "imp-verification.k"
main-module = "IMP-VERIFICATION"
syntax-module = "IMP-VERIFICATION-SYNTAX"