name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/k'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update Dependency Versions'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Install uv'
        uses: astral-sh/setup-uv@v6
      - name: 'Update kframework release tag'
        run: |
          K_VERSION=$(cat deps/k_release)
          sed -i 's!    "kframework==[0-9\.]*"!    "kframework=='${K_VERSION}'"!' pyproject.toml
          uv lock --upgrade
          git add pyproject.toml uv.lock
          git commit -m "Sync uv files: kframework ${K_VERSION}" || true
      - name: 'Push updates'
        run: git push
